apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: code-server
  name: code
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: code-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: code-server
    spec:
      containers:
      - image: ghcr.io/aaqaishtyaq/code:1
        name: vscode
        ports:
        - containerPort: 3000
